
PATH="/minerva/"
CLUSTER_PATH=PATH+"kubeCluster/"
CREATE_CLUSTER_PATH=CLUSTER_PATH+"create"
DELETE_CLUSTER_PATH=CLUSTER_PATH+"delete"
GET_CLUSTER_INFO=CLUSTER_PATH+"<clusterName>/info"

NAMESPACE_PATH="mlCluster/"
CREATE_FRAMEWORK=CLUSTER_PATH+NAMESPACE_PATH+"create"

ML_CLUSTER=CLUSTER_PATH+NAMESPACE_PATH+"<clusterName>"
ADD_NODE_KUBE_CLUSTER=CLUSTER_PATH+"clusterName/addNode"
